### ISSUE TITLE
Loadouts aren't JIP compatible

### ISSUE THREAD

**Issue by jameslkingsley** [ARCOMM/ARCMF#10]
When loading into the game for the first time (dedicated server) your loadout is applied. If you exit, pick another slot and load back in your loadout isn't applied.

**Comment by CER10TY** [comment]
Can't reliably test this without ftp access to the server but I've narrowed it down - the init of the unit doesn't roll out when JIP joins. You can test this by outputting the player's group - it's some jibberish when using JIP and only proper when joining for the first time.

Might or might not have something to do with A3s new inventory changes, although it works for the regular F3. I hate this.

**Comment by jameslkingsley** [comment]
Ah very interesting... If the init code is there but isn't executed we could just run a `call compile` on it. Also I'll speak to fbi about server access.

**Comment by jameslkingsley** [comment]
Hmm well `processInitCommands` is disabled in Arma 3 for some reason. I've added a simple bit to `initPlayerLocal.sqf` to just apply the rifleman loadout if the player is JIP and hasn't got a loadout assigned.

**Comment by jameslkingsley** [comment]
Okay so it works fine. Might as well just leave it as is and accept that JIP loadouts are going to be defaulted to rifleman/whatever the mission maker sets.

**Comment by jameslkingsley** [comment]
Gonna put this on the back burner though...

**Comment by ahousuke** [comment]
I think tryteyker is right on the money with this, eden complied missions dont seen to run the unit int on jip users (this also effects the f3 missions that where made in eden as we saw Saturday 3/5/16) 

other users have reported the issue also 
https://forums.bistudio.com/topic/188344-eden-3d-jip-init-not-firing/

looks like a bis fault and fingers crossed the fix it
