### ISSUE TITLE
Update medical gear for loadouts

### ISSUE THREAD

**Issue by Freddo3000** [ARCOMM/ARCMF#100]
### Rifleman
|Item|Amount
|---|---
|Field Dressing|3
|Morphine|1
|Tourniquet|1

### Combat Life Saver
|Item|Amount
|---|---
|Field Dressing|10
|Tourniquet|5
|Morphine|5
|Epinephrine|5
|Splint|5
|Saline 250mL|5
|Saline 500mL|2

### Medic
|Item|Amount
|---|---
|Field Dressing|30
|Tourniquet|7
|Morphine|15
|Epinephrine|15
|Splint|20
|Saline 250mL|8
|Saline 500mL|10
|Saline 1000mL|4

https://docs.google.com/document/d/1vxyQSLEjB23ZDdZGHClXrOxN90SHbu26bEUXjq7fqLE/edit

**Comment by BorderKeeper** [comment]
CLS Field Dressing put as 15 as 10 is way too low, since most emergencies require 2-3 on average from the old system.
Uniform increased from 3 to 5 from the above for the same reasons.

https://github.com/ARCOMM/ARCMF/pull/102
