### ISSUE TITLE
ACE weather validation

### ISSUE THREAD

**Issue by jameslkingsley** [ARCOMM/ARCMF#15]
In order to fix the crazy wind problem, the mission must have wind set to manual. This enhancement basically needs to execute some `preInit` code to forcefully switch wind to manual.

**Comment by CER10TY** [comment]
What crazy wind problem are we talking about here? Right now I'm not even sure how the framework currently handles weather since the original F3 had weather params and they're gone.

**Comment by jameslkingsley** [comment]
In the new framework weather is handled purely by the mission settings (parameters may be added in later on). But the wind problem is where wind will suddenly go insane and cause things like trees to fall over etc.

**Comment by jameslkingsley** [comment]
Server side - mission doesn't need to be touched. Should now be fixed.
