### ISSUE TITLE
JIP players sometimes spawn as a seagull stuck on loading screen

### ISSUE THREAD

**Issue by jameslkingsley** [ARCOMM/ARCMF#19]
This is a weird bug. This needs extensive testing to locate the problem. Lots of `diag_log` to do. My theory is that a JIP player doesn't have the same attributes as a non-JIP player so when a dozen checks/waitUntil's for non-JIP attributes happens it pauses any further execution.

Doesn't happen when not in sandbox mode however (*respawn and sandbox disabled in `description.ext`*) so it may be coming from some extra respawn malarkey thrown in there or something to do with setting up the sandbox environment like teleporting player to starting position, group markers etc.

**Comment by ahousuke** [comment]
is this bug still present ? 

The patch rolled out on 3/3/16 has 
ENGINE:
    Fixed: Every second JIP client was spawned into a seagull
in its change log (https://dev.arma3.com/post/spotrep-00053)

**Comment by jameslkingsley** [comment]
We had problems last night with players joining in progress and being instantly killed upon spawn and then stuck in the loading screen. I later removed respawn on start and took out some `waitUntil` stuff and it seemed to fix it.
