### ISSUE TITLE
JIP players enter spectator mode

### ISSUE THREAD

**Issue by jameslkingsley** [ARCOMM/ARCMF#20]
JIP players enter spectator mode (tested on old framework however). This might be a quick fix but I doubt it. This could actually be related to #19 since I'm guessing JIP player has different attributes so the game thinks it's a dead player thus entering spectator on spawn - unless that's the behavior of respawn type 4 ("GROUP").

**Comment by ahousuke** [comment]
Can we confirm what conditions this bug presents, we had active and working jips on Saturday 3/5/16 during the one mission sandbar (if we ignore the gear issues) working with respawn 4 disableai 1.

we also had issues with lack of playable units during morbus mission "the package" i believe this forced you to add ai units for them to switch into.

Have we seen this issue in other missions?

**Comment by jameslkingsley** [comment]
I haven't seen this issue in other missions so it could be down to just the mission but apparently Golbs was joining into an empty slot on different teams and it was repeating the same thing.
