### ISSUE TITLE
gitattributes to ignore mission.sqm camera changes

### ISSUE THREAD

**Issue by jameslkingsley** [ARCOMM/ARCMF#23]
Currently the mission.sqm stores information about the camera in the Eden editor which means moving around in the editor will cause un-staged changes. We should be able to use gitattributes to ignore certain lines of code in the mission.sqm but I'm a git novice.

**Comment by CER10TY** [comment]
We can smudge/clean the .sqm every time it enters staging, but it would leave the file inherently different. It is easier to tell gitattributes to completely ignore a file, but specific lines of codes (especially config-style setup like the camera) is very hard.

**Comment by jameslkingsley** [comment]
Ah yeah okay, well then we'll just have to get used to it I suppose :(
