### ISSUE TITLE
ACRE Reveal to AI OP?

### ISSUE THREAD

**Issue by CER10TY** [ARCOMM/ARCMF#33]
I don't know how much testing went into the ACRE Reveal function recently but when I tested it a couple of months back, it was extremely overpowered in the sense that AI could hear you from a hundred meters away and immediately get a knowsAbout value of 1, which would lead to them tracking you through walls and being able to shoot immediately once you pop your head out. Just something to consider, again, don't know if this was tested beforehand or not.

**Comment by jameslkingsley** [comment]
I never tested it, perhaps we should make it default to disabled and let the mission maker do the testing if they need it.

**Comment by jameslkingsley** [comment]
Defaulted to disabled in 1.1.2.
