### ISSUE TITLE
AI setup and ai apply loadouts not zeus compatiable

### ISSUE THREAD

**Issue by ahousuke** [ARCOMM/ARCMF#34]
Ive not tested this on the server however both start both functions fn_setupAI and fn_applyLoadout that are called by xeh start with the line
if (!isServer) exitWith {};

Unfortunately all zeus placed units are local to the zeus controller. So this will always return true when zeus places units on a dedicated server .
It's worth testing as it cant be tested locally and needs to be uploaded onto the server to be sure.

If i had any ideas of a work around i would have submitted it befor the udpate sorry =<

**Comment by ahousuke** [comment]
nvm ive not checked the locality of the commands closing the ticket

**Comment by jameslkingsley** [comment]
Yeah I tested it on the server. Once a Zeus places a unit, it's then propagated to the server and down to all clients. Once it reaches the server and is spawned on the server the loadout is applied thus reducing the call to once per unit, otherwise it would be per client.
