### ISSUE TITLE
AI Gear not working for Zeus placed units on dedicated server

### ISSUE THREAD

**Issue by jameslkingsley** [ARCOMM/ARCMF#48]
An easy fix. When mission loads, units are created on server and the loadout applies. When Zeus spawns units they are local to the curator so the script exits. I can't really see any problems occurring from removing the `if (!isServer) exitWith {};`. Thoughts @CER10TY ?

**Comment by CER10TY** [comment]
What script are we talking about here? Gear assignment (fn_assignGear.sqf) only exits if unit is not local, and the individual gear scripts don't have any isServer checks (as they're #include'd).

**Comment by jameslkingsley** [comment]
Script is in `f\arc\ai\fn_applyLoadout.sqf`.

**Comment by CER10TY** [comment]
Ditching !isServer clause.

**Comment by jameslkingsley** [comment]
Fixed in 1.1.8.
