### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by jameslkingsley** [ARCOMM/ARCMF#53]
All feature requests go here.

**Comment by edelle** [comment]
The player map markers for your fireteam disappear 50 meters away from player position (radius for sthud is 50 meters)

**Comment by edelle** [comment]
Possibility to write different briefings for members of the same faction

**Comment by jameslkingsley** [comment]
Map markers for medics.

**Comment by edelle** [comment]
Increase fade range for Fireteam member markers cause atm they become unnecessary clutter on map

**Comment by edelle** [comment]
Revamp platoon roster with colours and shit

**Comment by edelle** [comment]
Add an option to remove ft member markers?

**Comment by jameslkingsley** [comment]
Closing this and moving it to ARCMF2.
