### ISSUE TITLE
Enhance default FT colours

### ISSUE THREAD

**Issue by edelle** [ARCOMM/ARCMF#74]
Example: A1 uses red and green, A2 blue and yellow etc.

Since we're using 3 6-man fireteams we'll have to review available colors.

**Edited by tryteyker/CER10TY for clarity**

**Comment by jameslkingsley** [comment]
This involves complications, especially since you'd be hard-coding the groups. Currently it loops over all the player groups and assigns colours based on their role. It's doable by calculating how many per group and keeping track of colours used.

**Comment by jameslkingsley** [comment]
Closing this and moving it to ARCMF2.
