### ISSUE TITLE
ACE Medical Functions

### ISSUE THREAD

**Issue by jameslkingsley** [ARCOMM/ARCMF#81]
Commonly used but always forgotten.
- [ace_medical_fnc_setStructuralDamage](https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_setStructuralDamage.sqf)
- [ace_medical_fnc_treatmentAdvanced_fullHealLocal](https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_treatmentAdvanced_fullHealLocal.sqf)
- [ace_medical_fnc_setHitPointDamage](https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_setHitPointDamage.sqf)

**Comment by hazardouschurch** [comment]
Depreciated
