### ISSUE TITLE
Slow camera speed when inside buildings

### ISSUE THREAD

**Issue by jameslkingsley** [ARCOMM/ARCMF#84]
Use this function https://github.com/marseditor/mars/blob/master/addons/common/functions/fnc_isInBuilding.sqf

Only when in free cam mode

**Comment by jameslkingsley** [comment]
Perhaps also slow camera speed based on altitude from ground level - low = slower, higher = faster.

**Comment by CER10TY** [comment]
This is already available in-engine through Splendid Camera.

**Comment by jameslkingsley** [comment]
You can't just tie the two together unfortunately, but it's simple to implement anyway.
